//! Regenerates the committed public-API surface snapshot
//! (`docs/public-api/whereat.txt`) on every `cargo test` run, so API
//! changes always show up as a git diff next to the code change that caused
//! them, and the surface size stays one glance away.
//!
//! Modes (`ZEN_API_DOC` env var — set per-job in CI workflows, see ci.yml):
//! - unset / `regen` → regenerate the file in place (local default; commit the diff)
//! - `check`         → regenerate to memory, FAIL if the committed file is stale
//! - `off`           → skipped (CI matrix jobs without nightly rustdoc / the tool)
//!
//! Two sections: default features, and "all features except `_*`" — every
//! feature from the manifest except underscore-prefixed ones, which are
//! internal/research gates and not public surface. The list is computed from
//! `cargo metadata`, so new features appear automatically.
//!
//! Requires `cargo-public-api` (0.52+) and a nightly toolchain for rustdoc
//! JSON: `cargo install cargo-public-api --locked && rustup toolchain install nightly`

use std::path::PathBuf;
use std::process::Command;

const CRATE: &str = "whereat";

fn run(args: &[&str]) -> Vec<u8> {
    let out = Command::new("cargo")
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .args(args)
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "failed to run cargo {} ({e}); for public-api: install with \
                 `cargo install cargo-public-api --locked` and ensure a nightly \
                 toolchain exists (`rustup toolchain install nightly`), or set \
                 ZEN_API_DOC=off to skip this test",
                args[0]
            )
        });
    assert!(
        out.status.success(),
        "cargo {} failed (set ZEN_API_DOC=off to skip):\n{}",
        args.join(" "),
        String::from_utf8_lossy(&out.stderr)
    );
    out.stdout
}

fn surface(feature_args: &[&str]) -> Vec<String> {
    let mut args = vec!["public-api", "-p", CRATE, "--simplified"];
    args.extend_from_slice(feature_args);
    String::from_utf8(run(&args))
        .expect("cargo public-api emitted non-UTF8")
        .lines()
        .map(str::to_owned)
        .filter(|l| !l.is_empty())
        .collect()
}

/// All manifest features except `default` and underscore-prefixed internal
/// gates, sorted for determinism.
fn public_features() -> Vec<String> {
    let meta: serde_json::Value =
        serde_json::from_slice(&run(&["metadata", "--no-deps", "--format-version", "1"]))
            .expect("cargo metadata JSON");
    let pkg = meta["packages"]
        .as_array()
        .expect("packages array")
        .iter()
        .find(|p| p["name"] == CRATE)
        .unwrap_or_else(|| panic!("{CRATE} not in workspace metadata"));
    let mut feats: Vec<String> = pkg["features"]
        .as_object()
        .expect("features map")
        .keys()
        .filter(|k| *k != "default" && !k.starts_with('_'))
        .cloned()
        .collect();
    feats.sort();
    feats
}

#[test]
fn public_api_surface_doc_is_current() {
    match std::env::var("ZEN_API_DOC").as_deref() {
        Ok("off") => {
            eprintln!("ZEN_API_DOC=off — public-API snapshot regen skipped by caller");
            return;
        }
        Ok("check") | Ok("regen") | Err(_) => {}
        Ok(other) => panic!("unknown ZEN_API_DOC value {other:?} (off|check|regen)"),
    }
    let check = std::env::var("ZEN_API_DOC").as_deref() == Ok("check");

    let features = public_features();
    let feature_csv = features.join(",");
    let sections: [(&str, Vec<&str>); 2] = [
        ("default features", vec![]),
        (
            "all features except _*",
            if features.is_empty() {
                vec![]
            } else {
                vec!["--features", &feature_csv]
            },
        ),
    ];

    let mut doc = String::new();
    doc.push_str(&format!(
        "# {CRATE} public API surface\n\
         # Generated by tests/public_api_doc.rs via `cargo public-api --simplified`\n\
         # (regenerated on every `cargo test`; ZEN_API_DOC=check verifies, =off skips).\n\
         # Underscore-prefixed features are internal and excluded from the\n\
         # all-features section.\n\
         # DO NOT EDIT BY HAND — commit regenerated changes together with the code.\n"
    ));
    for (label, extra) in &sections {
        let items = surface(extra);
        doc.push_str(&format!("\n## {label} ({} items)\n\n", items.len()));
        for line in &items {
            doc.push_str(line);
            doc.push('\n');
        }
        eprintln!("{CRATE} [{label}]: {} public items", items.len());
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("docs/public-api")
        .join(format!("{CRATE}.txt"));
    let existing = std::fs::read_to_string(&path).ok();

    if check {
        assert_eq!(
            existing.as_deref(),
            Some(doc.as_str()),
            "committed public-API snapshot is stale: run `cargo test` locally \
             and commit the regenerated {}",
            path.display()
        );
        return;
    }

    if existing.as_deref() != Some(doc.as_str()) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &doc).unwrap();
        eprintln!(
            "regenerated {} — review and commit the diff",
            path.display()
        );
    }
}
